### ISSUE TITLE
Use Gadle source dependencies instead of workspace repo

### ISSUE THREAD

**Issue by ErikHellman** [readium/r2-testapp-kotlin#142]
Starting from Gradle 4.10, there is support for source dependencies in Gradle (see https://blog.gradle.org/introducing-source-dependencies). This allows a module to declare a dependency on Gradle module through a git URL, which will then be built when needed.

This would make the setup for Android/Kotlin much simpler as it removes the need for the workspace repo and developers could be the testapp without having to checkout all the other repos locally.

**Comment by prsolucoes** [comment]
Hi,

I tried it but without success:

```
sourceControl {
        gitRepository('https://github.com/ubook-editora/r2-navigator-kotlin.git') {
            producesModule('com.github.readium:r2-navigator')
        }
}
```

```
implementation('com.github.readium:r2-navigator') {
        version {
            branch = 'develop'
        }
}
```

But only get error:

```
Problems reading data from Binary store in /private/var/folders/64/9s0r4g290ns84t9wbzj047qr0000gn/T/gradle7098206698374636763.bin (exist: true)
```

**Comment by aferditamuriqi** [comment]
the workspace repo is not really needed by default. it is only to give a quick start into R2, any experienced developer can set up their own development environment and use the repos or dependencies as needed and fit into their own routine.

the testapp can be also used as a starting point as is, but a developer or implementer can just implement the R2 functionalities into their own app and use the testapp as a reference. 

several updates and improvements have been done since this issue was first filed and since it doesn't apply anymore, I'll close this
