### ISSUE TITLE
about horizontal scroll issue

### ISSUE THREAD

**Issue by hellcan** [readium/r2-testapp-kotlin#2]
I met this problem.

When I am try to slide to the next page. The page is over slide and can not stop at the right place. So how can I fix it?

![issue](https://user-images.githubusercontent.com/7111856/34605392-882a3934-f1af-11e7-8d89-d4a7e2475e58.gif)

**Comment by llemeurfr** [comment]
Wahoo, you're the first external tester of this work in progress. We decided that it would be good to expose this alpha version for bringing together a community of Android developers around this Readium-2 architectured reading system. I hope you'll be one member of this community. Even if the fundamentals are good, this dev is far from being finished.

The snap points on Android are not as easy to implement as in iOS. @aferditamuriqi is working on it, ideas are welcome.

**Comment by HadrienGardeur** [comment]
@hellcan do you also experience this same issue when tapping instead of swiping?

**Comment by HadrienGardeur** [comment]
Basically, I think (correct me if I'm wrong @aferditamuriqi) that this is how swipe works currently:

- the current webview is fully scrollable, which means that if you swipe quickly you could go beyond the next page
- once you've stopped swiping, it attempts to snap the view to the closest page (using total width of the document divided by the width of the device)

Ideally we want a slightly different behaviour:

- swiping shouldn't go beyond the next page
- snapping should be smooth (animation) instead of a jump to the next snap point

**Comment by hellcan** [comment]
![issue2](https://user-images.githubusercontent.com/7111856/34631207-6e296fbe-f213-11e7-855f-0fb3c084e02f.gif)

Thank you for response.
This is how the tapping looks like.
If the first page is not over slide, the next one works totally fine.

**Comment by HadrienGardeur** [comment]
It's worth pointing out that this is entirely handled in JS using https://github.com/readium/r2-testapp-kotlin/blob/master/r2-testapp/src/main/assets/ReadiumCSS/utils.js

We plan on having calls between the teams working with native (Swift, Kotlin) code and our JS developers in early 2018 to figure out a good strategy for cross platforms touch handling.

**Comment by hellcan** [comment]
![image](https://user-images.githubusercontent.com/7111856/34716246-5853898c-f4d3-11e7-9603-5463349ecc3b.png)

![image](https://user-images.githubusercontent.com/7111856/34716326-9c6e8f5e-f4d3-11e7-830c-9fdbaff68e8f.png)


Hello,
I used Chrome remote debug tool today, and find out snap( ) missing in utils.js, which is the reason cause page is over sliding?
