### ISSUE TITLE
Epub content is out of screen

### ISSUE THREAD

**Issue by prsolucoes** [readium/r2-testapp-kotlin#214]
Hi,

After pass some pages, the epub content is going out of screen:

MY EBOOK:
![image](https://user-images.githubusercontent.com/395096/60101996-35029a00-9733-11e9-931b-b69a15485346.png)

READIUM NATIVE EBOOK (Dead Souls):
![image](https://user-images.githubusercontent.com/395096/60102112-7430eb00-9733-11e9-85ee-487484d32e66.png)

This is not specific with an ebook, but with all ebooks.

Thanks.

**Comment by SwiiZe** [comment]
Hi could you provide more informations about your device and android version please.

**Comment by prsolucoes** [comment]
Hi,

Motorola G7 Play. Android 9.

I have created a video showing the flow:
https://www.dropbox.com/s/6eg25czq9n97mbv/readium-error.mp4?dl=1

The problem only start happen when you scroll the page to left/right instead of click on side left/right. If you drag from right to left the page start going to left and the problem happens.

Thanks.

**Comment by Irteza-S** [comment]
I can reproduce the bug but I have not managed to fix it yet.

**Comment by Sought** [comment]
I found where the issue comes from. For a reason that is not yet known to me, the scrollable content width of the webview is not consistent on most devices. Sometimes it is a multiple of the device width which is how it should be. However sometimes it is a multiple of the device width + 1 or 2 pixels. It ends up misaligning the columns.

It should be quickly fixed.
