### ISSUE TITLE
About progress?

### ISSUE THREAD

**Issue by hellcan** [readium/r2-testapp-kotlin#3]
Hi there， 

Is there anyway to keep track of reading history of the book? Thank you

**Comment by llemeurfr** [comment]
This would be an interesting project, to be discussed for all implementations (therefore in the [readium-2](https://github.com/readium/readium-2) repo),, but **tricky**. 

First, this  is mostly an app level issue, as the reading engine would only notify of reading event. And our open-source test app is ... a test app. 

Second, and really important, in the spirit of an open-source project, an app should **never** use such info without the knowledge and supervision of its user (and European laws will enforce this more and more). Therefore an open-source app module could be develop for the benefit of all readium-2 based apps, but with this spirit in mind.

**Comment by HadrienGardeur** [comment]
Just a quick note:

- the hardest thing to track are events where the user skips ahead or back in a publication
- these events can be triggered by a link (for instance a footnote) as well as other means of navigating the publication (table of contents or search)
- in the case of links, we need to make sure that we have a callback that the app can catch to provide the proper UX (for instance a back button)
- in the case of the ToC and search, the app should already be aware since it controls such events
