### ISSUE TITLE
Can we set android:usesCleartextTraffic="false" and still have the ebook reader work ?

### ISSUE THREAD

**Issue by ghost** [readium/r2-testapp-kotlin#337]
This flag `android:usesCleartextTraffic="true"` seems like has a security issue. But if this is not enabled, the app crashes and the ebook reader doesn't open the epub (epub opened is blank)

https://github.com/readium/r2-testapp-kotlin/blob/develop/r2-testapp/src/main/AndroidManifest.xml#L28

As per Google's Android document - https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic
```The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.```

So, do we have an alternative to this flag "android:usesCleartextTraffic", so that we can set it to `false` and still make the ebook reader work ? else the whole Android application traffic would be cleartext traffic.

**Comment by mickael-menu** [comment]
Thanks for reporting this issue @mooka-ventures 

We need cleartext traffic enabled because the internal HTTP server used to serve EPUB publications (NanoHttpd) is not configured for HTTPS. However, apparently there's a way to use HTTPS with it by generating a self-signed certificate: https://github.com/edrlab/nanohttpd#generating-an-self-signed-ssl-certificate.

It might be worth investigating, however this is not a high priority issue for now and I don't know when we'll be able to take a look at it. But feel free to investigate this issue yourself and submit a PR if this is a problem for you.

**Comment by mooka-ventures** [comment]
Noted. Thanks @mickael-menu . Will try the self-signed-certificate approach for now.

**Comment by mickael-menu** [comment]
We have plans to replace the HTTP server, see https://github.com/readium/r2-testapp-kotlin/issues/297

However, fetching the LCP CRL might still require clear text traffic until it is served as HTTPS: https://github.com/readium/r2-lcp-kotlin/issues/59

**Comment by mickael-menu** [comment]
You can fine-tune the cleartext traffic rules to allow only the domains used by Readium, as showcased here: https://github.com/readium/r2-testapp-kotlin/pull/380

**Comment by mickael-menu** [comment]
A side effect from the above fix is that if an OPDS feed uses `http` instead of `https`, it won't be supported. It's a decision to be taken by reading apps.
