### ISSUE TITLE
Read epub using byte array (byte[]) instead of file path

### ISSUE THREAD

**Issue by munnadroid** [readium/r2-testapp-kotlin#343]
Hi,

While reading the epub file, is it possible to replace the file path by bytes of file? I see a lot of uses of the epub file path in r2-test-app and other library modules as well.

I am using the 'develop' branch.

**Comment by mickael-menu** [comment]
This is not possible at the moment, although if there's a valid use case, we could offer the possibility of [providing a leaf `Fetcher`](https://github.com/readium/architecture/blob/master/proposals/002-composite-fetcher-api.md) to the `Streamer` to handle custom read access for the parsers.

However, [`ZipFile`](https://developer.android.com/reference/kotlin/java/util/zip/ZipFile) seems to only work with `File`, no in-memory buffers. So you would have to handle the parsing of the ZIP buffer through other means.

Can you explain a bit more why you need to use byte arrays instead of files?

**Comment by munnadroid** [comment]
I have received bytes of book from a source but I do not want to store to a file in local storage. Rather pass the byte array to the parser and read an ebook.

Yeah, ZipFile seems to only work with File. I have found [this](https://stackoverflow.com/questions/61652063/how-to-parse-a-zipped-file-completely-from-ram/) but I have not succeeded yet.

**Comment by mickael-menu** [comment]
Version `2.0.0-beta.1` now ships with [`PublicationAsset`](https://github.com/readium/r2-shared-kotlin/pull/133) which can be used to implement custom file access.
