### ISSUE TITLE
How to show current page number in EpubActivity

### ISSUE THREAD

**Issue by mahdisadeghi74** [readium/r2-testapp-kotlin#362]
how to show current number of page like : 10 / 30
I use  **"${locator.locations.position ?: 0}/${positionCount}"** but it is not show page number 

I want add SeekBar inside activity for go to specific page and show :(current page of total page)

**Comment by mickael-menu** [comment]
Unfortunately we can't display the exact number of screen-pages, because it depends on the screen size, user settings, etc. So we can't determine them expect for the currently loaded chapter/resource. Using `positions` is the closest you can get from something similar to real page numbers.

Note that some apps like iBooks display real screen/page numbers, but they recompute it every time the user settings change and it takes some time – you can see a progress bar when that happens. It's something that we don't support in Readium and have no plan of supporting in the foreseeable future.

**Comment by mahdisadeghi74** [comment]
I fixed it:) it is so simple:)

I find pageStatus with below code inside **utils.js**:
```
var getPageNumber = function(){
    var scrollWidth = document.scrollingElement.scrollWidth;

    if ( window.scrollX === null || window.innerWidth === null)
        return 0

    return Math.floor(Math.abs(window.scrollX / window.innerWidth));
}

var getPageCount = function(){
    var scrollWidth = document.scrollingElement.scrollWidth;

    if ( scrollWidth === null || window.innerWidth === null)
        return 0

    return Math.floor(Math.abs(scrollWidth / window.innerWidth));
}
```
then call bellow code inside `window.addEventListener('scroll', function(e){` :

`         Android.progressionPageNumber(pageNumber, pageCount);`

After that i call `findPage()` inside `currentLocator.observe` and `onPageLoaded()`:

 ```
   @SuppressLint("SetTextI18n")
    private fun findPage() {
        var allPages = 0
        var exactPageNumber = 0
        CoroutineScope(IO).launch {

            resourcePager.offscreenPageLimit = publication.readingOrder.size
            (resourcePager.adapter as R2PagerAdapter).mFragments?.forEach { key, value ->

                val count = (value as R2EpubPageFragment).webView.numPages
                Log.d("TAG", "onViewCreated: numpages: $key /// $count")
                allPages += count

                if (key.toInt() == resourcePager.currentItem - 1)
                    exactPageNumber = allPages + pageNumber

            }

            CoroutineScope(Main).launch {
                binding?.textPageNumber?.text = if (allPages > 0) "${(exactPageNumber) + 1} / $allPages" else {
                    findPage()
                    ""
                }
            }
        }

    }
```

> **it show me exact page number without performance problems**
