### ISSUE TITLE
Unchecked checkbox showing different icons on different phones

### ISSUE THREAD

**Issue by UniSIM** [readium/r2-testapp-kotlin#364]
Hello,

I was testing the application on a Samsung phone and a Huawei phone and realised that the icon for the unchecked checkbox is showing differently. 

Samsung
![Samsung](https://user-images.githubusercontent.com/3793114/96411787-9d746500-121b-11eb-88d5-001c494d1105.jpg)

Huawei
![Huawei](https://user-images.githubusercontent.com/3793114/96411799-a36a4600-121b-11eb-88be-7de2668d745c.jpg)

Is this a bug or other issue?
Thank you!

**Comment by mickael-menu** [comment]
I don't think it's related to Readium, we don't have any customization regarding this.

My guess is that the book uses particular characters or fonts instead of regular checkbox, that render differently on Samsung.

You can try [this publication](https://github.com/readium/r2-testapp-kotlin/files/5399890/touchHandling.epub.zip) which contains regular HTML checkboxes.

**Comment by UniSIM** [comment]
Okay thanks!
