### ISSUE TITLE
How can I skip passphrase dialog

### ISSUE THREAD

**Issue by RomanSoviak** [readium/r2-testapp-kotlin#400]
I have lcp test lib and test app, user hashed password.

How can I skip ask passphrase dialog. And put hashed password for logged in user. 

This dialog is from lcp library. So I cannot do something with UI. Thanks!

**Comment by mickael-menu** [comment]
If you already have the passphrase in your app, instead of using the `LcpDialogAuthentication`, you can use the `LcpPassphraseAuthentication`. It takes a fallback `LcpAuthenticating` which I suggest to set to `LcpDialogAuthentication`, in case the passphrase is wrong. Otherwise the user will not be able to open the book.

```kotlin
val authentication = LcpPassphraseAuthentication(
    passphrase = ...,
    fallback = LcpDialogAuthentication()
)
```

You can also create your own `LcpAuthenticating` implementation to get the passphrase from a database, for example. 

You can provide this object to two different APIs:

* To the factory of the LCP content protection. This will be used for all the publications opened with the `Streamer`, so it might not be appropriate with a single passphrase. But it can work if you implement your own `LcpAuthenticating`.
    ```kotlin
    lcpService.contentProtection(authentication)
    ```
* To `retrieveLicense()`, which can be useful to preload a LCP passphrase after acquiring the publication, for example:
    ```kotlin
    lcpService.retrieveLicense(file, authentication)
    ```

**Comment by RomanSoviak** [comment]
Thanks a lot. What about hashed passphrase?

**Comment by mickael-menu** [comment]
`LcpPassphraseAuthentication` takes both clear and hashed passphrases.
