### ISSUE TITLE
Wrong pages count 

### ISSUE THREAD

**Issue by RomanSoviak** [readium/r2-testapp-kotlin#412]
@mickael-menu my TextView uses the following code:
locator.locations.position.toString() + " / " + positionCount.toString()

https://user-images.githubusercontent.com/26696190/115833562-dc7ab180-a41c-11eb-84f5-53d5be8078c8.mp4

**Comment by mickael-menu** [comment]
It looks correct to me. If you are referring to the fact that we are jumping sometimes two positions, that's normal.

On a reflowable EPUB, the number of "screen pages" depends on the screen size, font size, user settings, etc. So our `positions` cannot match the screen pages because that would mean reprocessing this information on the whole book every time the pages are reflowed. Readium `positions` are fixed and so sometimes you can have several positions on a given screen page, or one position for several screen pages.

**Comment by csantanu** [comment]
@RomanSoviak Hi, can you please help me pointing out where, I should add the above code to get the page numbers displayed ? I am using the latest V2.2 code. Thanks in advance.

**Comment by pranjalpc99** [comment]
@RomanSoviak How did you get the total page count?

**Comment by RomanSoviak** [comment]
@pranjalpc99 `publication.positions().size`
