### ISSUE TITLE
E-book Text select/highlight feature is not working after update to 2.0.0 from 2.0.0-beta.2

### ISSUE THREAD

**Issue by nareshsvn** [readium/r2-testapp-kotlin#414]
We have updated our R2 project to the 2.0.0 version from 2.0.0-beta.2. After the update, the text select/ highlight feature is not working.
In 2.0.0-beta.2 version text select/ highlight feature is working but the text selection has the issue (after selecting the text, if the user highlights that text with color, then text selection going to below).

Thanks,
Naresh

**Comment by mickael-menu** [comment]
Is the publication you are testing with protected with a DRM like LCP? If yes, then it's because [we have disabled text selection to prevent unrestricted user copy](https://github.com/readium/r2-streamer-kotlin/pull/141).

Until we find a better solution and **ONLY if your app doesn't show a Copy editing action for LCP protected publications**, you can disable the fix by registering the following custom CSS when initializing the `Server` in your app.

```kotlin
server.loadCustomResource("""
        * {
            user-select: auto !important;
            -webkit-user-select: auto !important;
        }
    """.byteInputStream(), "fix-select.css", Injectable.Style)
```

**Comment by nareshsvn** [comment]
Yes. we are testing with epub which is protected with an LCP DRM. Thanks a lot for your help.

Naresh
